kind: pipeline
type: docker
name: greeting

steps:
- name: Message
  image: alpine
  commands:
  - echo hello
  - echo world

- name: Drone
  image: alpine
  commands:
  - echo This is Drone Sample Project
  - echo

- name: OS_Version
  image: ubuntu
  commands:
  - os_version=`uname`
  - echo "os_version is = $os_version"

- name: Apache2
  image: ubuntu
  commands:
  - apt-get update-y
  - apt-get install apache2 curl -y
  - service apache2 start
  - IP_ADD=`/sbin/ifconfig eth0 | grep 'inet' | cut -d: -f2 | awk '{print $2}'`
  - curl $IP_ADD
