kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello
  - echo world

- name: es
  image: alpine
  commands:
  - echo Drone
  - echo Sample Project

- name: fr
  image: alpine
  commands:
  - os_version=`uname`
  - echo "os_version is = $os_version"
