kind: pipeline
type: docker
name: greeting

steps:
- name: Message
  image: alpine
  commands:
  - echo hello
  - echo world

- name: Drone
  image: alpine
  commands:
  - echo This is Drone Sample Project
  - echo

- name: OS_Version
  image: ubuntu
  commands:
  - os_version=`uname`
  - echo "os_version is = $os_version"
